### ISSUE TITLE
MQTT Binary Sensor bug

### ISSUE THREAD

**Issue by JemRF** [home-assistant/supervisor#1688]
The following example does not work.

https://www.home-assistant.io/integrations/binary_sensor.mqtt/
 
```
# Example configuration.yaml entry
binary_sensor:
  - platform: mqtt
    name: "Window Contact Sensor"
    state_topic: "home-assistant/window/contact"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "home-assistant/window/availability"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    device_class: opening
    value_template: '{{ value.x }}'
```
The offline/offline functionality works but the off/on functionality does not work with the following example provided in the :

` mosquitto_pub -h 127.0.0.1 -t home-assistant/window/contact -m "OFF"

This can be fixed by removing the last line:
  `  value_template: '{{ value.x }}'`

I do not know why removing the last line fixes the issue and cannot find explanation online therefore I think its a bug.
