### ISSUE TITLE
auth failing

### ISSUE THREAD

**Issue by tsvi** [home-assistant/supervisor#1694]
**Home Assistant release with the issue:**

```
arch | aarch64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.114-v8
python_version | 3.7.7
timezone | Asia/Jerusalem
version | 0.109.2
virtualenv | false
```

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

**Description of problem:**

1. In the system log I get the following error once every 5 minutes:

`20-05-03 09:23:39 ERROR (MainThread) [supervisor.auth] Can't request auth on Home Assistant!`

2. Every time I login I get the following notification:

Login attempt or request with invalid authentication from 172.30.32.2 (that's the reverse proxy

I have a reverse proxy setup with Nginx Proxy Manager and have the following in my config:

```
http:
  base_url: !secret hass_uri
  use_x_forwarded_for: true
  trusted_proxies:
  - 172.16.0.0/24
```
