### ISSUE TITLE
Enabling syslog in dockers daemon.json causes bootloop

### ISSUE THREAD

**Issue by timdonovanuk** [home-assistant/supervisor#1783]
**Home Assistant release with the issue:**

Latest 

**Operating environment (HassOS/Generic):**

HassOS on Proxmox

**Description of problem:**

HA should support logging to remote syslog.

To attempt to enable this, you should be able to simply swap out the docker logging driver from the default, to syslog. To do this, [you create a file /etc/docker/daemon/json with the following:](https://docs.docker.com/config/containers/logging/syslog/)

```
{
  "log-driver": "syslog",
  "log-opts": {
    "syslog-address": "udp://1.2.3.4:1111"
  }
}
```

This however causes the supervisor to bootloop, with the error:

`[FAILED] Failed to start Docker Application Container Engine.`

I suppose HA Supervisor is set to auto reboot if Docker does not start, as I cannot debug the error, the OS just reboots a few seconds after that line is printed to console.

**Comment by timdonovanuk** [comment]
To get daemon.json read and used, I tried also `systemctl restart docker.service` rather than rebooting, but it seems like the moment docker no longer starts a forced reboot happens.

**Comment by pvizeli** [comment]
We only support journald logging type on Supervisord or Home Assistant OS

**Comment by timdonovanuk** [comment]
@pvizeli could this not be kept as an enhancement suggestion? Remote syslog is a pretty standard way of logging things, I'd thought its obvious why shipping logs remotely is beneficial.

I suppose alternatively I can install syslog in a docker container inside the OS and suck up ha.log, but it'll miss out on the OS and supervisor level logs.

**Comment by timdonovanuk** [comment]
FWIW I got this working by installing the portainer addon, and starting a container like the following:

```
  syslogng:
    container_name: syslogng
    image: bobrik/syslog-ng
    volumes:
      - /mnt/data/supervisor/homeassistant/home-assistant.log:/var/log/home-assistant.log:ro    
      - /mnt/data/supervisor/homeassistant/syslog-ng:/etc/syslog-ng
    environment:
      - PUID=1000
      - PGID=1000
```

I then created the folder and file in the HA config directory /syslog-ng/syslog-ng.conf like below:

```
@version: 3.6

options {
    use_dns(no);
    keep_hostname(yes);
    create_dirs(yes);
    ts_format(iso);
};

source s_homeassistant {
 file("/var/log/home-assistant.log" program-override("homeassistant"));
 };

destination d_remotesyslog {
  syslog("<your remote syslog host>" transport("udp") port("514"));
};

log {
    source(s_homeassistant);
    destination(d_remotesyslog);
};
```

This will at least ship home-assistant.log off to a remote syslog server.

**Comment by trident25** [comment]
I too would really like to see the ability to send Docker logs to Syslog. Thanks for the workaround @timdonovanuk

**Comment by WisdomWolf** [comment]
@timdonovanuk That solution works perfectly!  It also made me realize that if we are running a docker container alongside the others we can just collect the logs for all components directly from the docker socket.  I use logspout for exactly this purpose in both my Kubernetes cluster and my Docker swarm.  I ship my logs to Papertrail, but I imagine that any syslog host would work similarly.  I can confirm that this method will ship not just homeassistant logs, but logs for all addons and supervisor.

_Note: This image won't work on ARM devices like Raspberry Pi, but you can compile an ARM image or use mine by replacing the image with `wisdomwolf/logspout`_

```
logspout:
  container_name: papertrail_logspout
  image: gliderlabs/logspout
  command: syslog+tls://<hostname>:<port>
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - PUID=1000
    - PGID=1000
  restart: unless-stopped
```

Also, for anyone else that stumbles on here, you can add this under the **Stack** section of Portainer.
