### ISSUE TITLE
last_changed error on device naming 0x000

### ISSUE THREAD

**Issue by tuanha2000vn** [home-assistant/supervisor#2361]
## Work fine on normal device
```
Last changed {{ states.binary_sensor.alarm_control_panel_armed.last_changed }}
``` 
```
Result: Last changed 2020-12-10 12:46:25.990941+00:00
```
---
## Not work on device name like this 0x086 (any zigbee2mqtt device)
```
Last changed {{ states.binary_sensor.0x086bd7fffeeec4b0_occupancy.last_changed }}
```
Result:
```
TemplateSyntaxError: expected token 'end of print statement', got 'x086bd7fffeeec4b0_occupancy'
```
---
## Make a binary device template and it work fine again
```
  sensors:
    contact_c300_tuya:
      device_class: door
      value_template: "{{ is_state('binary_sensor.0x086bd7fffeeec4b0_occupancy', 'on') }}"
```
```
Last changed {{ states.binary_sensor.contact_c300_tuya.last_changed }}
``` 
Result: 
```
Last changed 2020-12-10 12:46:25.990941+00:00
```
