### ISSUE TITLE
Validation requires objects/arrays to always exist

### ISSUE THREAD

**Issue by mKeRix** [home-assistant/supervisor#2559]
**Describe the issue you are experiencing**

An object or an array that is defined in the schema always needs to be present in the options, even if all its properties are optional. This leads to add-on default configs looking like this:

```yaml
global:
  instanceName: changeme
  integrations:
    - bluetoothLowEnergy
cluster:
  autoDiscovery: false
  peerAddresses: []
bluetoothLowEnergy:
  allowlist: []
  denylist: []
bluetoothClassic:
  addresses: []
omronD6t: {}
gridEye: {}
homeAssistant: {}
```

To grant my users the same experience across all platforms I would expect to see something like this work:

```yaml
global:
  instanceName: changeme
  integrations:
    - bluetoothLowEnergy
```

As soon as you remove any of the keys specified in the default above you are met with the following error:

```txt
Failed to save addon configuration, not a valid value for dictionary value @ data['options']
```

You can find the sample schema [here](https://github.com/mKeRix/hassio-repo/blob/master/room_assistant/config.json).

**What is the used version of the Supervisor?**

supervisor-2021.02.6

**What type of installation are you running?**

Home Assistant Supervised

**Which operating system are you running on?**

Debian

**What is the version of your installed operating system?**

9.13

**What version of Home Assistant Core is installed?**

core-2021.2.1

**Steps to reproduce the issue**

1. Add my add-on repo: https://github.com/mKeRix/hassio-repo
2. Install the room-assistant add-on.
3. Try to remove any of the empty object or empty array properties, then save.

**Anything in the Supervisor logs that might be useful for us?**

_No response_

This issue is aftermath of #2540, more info for this specific add-on can be found at mKeRix/room-assistant#501.
