### ISSUE TITLE
mqtt addon logins password cannot be configured with passwords from secrets.yaml

### ISSUE THREAD

**Issue by pbzdyl** [home-assistant/supervisor#2904]
### Describe the issue you are experiencing

I cannot configure MQTT addon logins with passwords fetched from HA's secrets.yaml file

### What is the used version of the Supervisor?

supervisor-2021.04.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 5.13

### What version of Home Assistant Core is installed?

core-2021.5.4

### Steps to reproduce the issue

```yaml
logins:
  - username: mqtt
    password: !secret mqtt_password
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
anonymous: false
```

However, the config editor in the Add-on GUI in Supervisor shows 'Invalid YAML' message and doesn't allow saving the config.

I've originally reported this issue in the [addons repo](https://github.com/home-assistant/addons/issues/2015) but [according to @frenck](https://github.com/home-assistant/addons/issues/2015#issuecomment-844270855), this should be instead reported here.

### Anything in the Supervisor logs that might be useful for us?

```txt
Nope, this is blocked on the UI level.
```
