### ISSUE TITLE
Supervisor cannot update b/c cannot resolve docker registry

### ISSUE THREAD

**Issue by ahgraber** [home-assistant/supervisor#2990]
### Describe the issue you are experiencing

Supervisor update fails:
```
21-07-01 14:04:35 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install homeassistant/aarch64-hassio-supervisor:
2021.06.6: 500 Server Error for http+docker://localhost/v1.40/images/create?tag=2021.06.6&fromImage=homeassistant%2Faarch64-hassio-supervisor: 
Internal Server Error ("Get "https://registry-1.docker.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)")
```

I have already tried `ha su repair` and `ha su restart` and have restarted the host several times.

### What is the used version of the Supervisor?

supervisor-2021.6.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.13

### What version of Home Assistant Core is installed?

core-2021.6.2

### Steps to reproduce the issue

Update fails with same error regardless of whether I try to update in the gui or using `ha su update`.

### Anything in the Supervisor logs that might be useful for us?

```txt
'''
21-07-01 14:04:20 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/update access from core_ssh
21-07-01 14:04:20 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor.txt
21-07-01 14:04:20 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor
21-07-01 14:04:20 INFO (MainThread) [supervisor.host.services] Reloading local service hassos-apparmor.service
21-07-01 14:04:20 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2021.06.6
21-07-01 14:04:20 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-hassio-supervisor with tag 2021.06.6.
21-07-01 14:04:21 WARNING (MainThread) [supervisor.host.network] Can't update connectivity information: Error: Timeout was reached
21-07-01 14:04:35 ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install homeassistant/aarch64-hassio-supervisor:2021.06.6: 500 Server Error for http+docker://localhost/v1.40/images/create?tag=2021.06.6&fromImage=homeassistant%2Faarch64-hassio-supervisor: Internal Server Error ("Get "https://registry-1.docker.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)")
21-07-01 14:04:35 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install homeassistant/aarch64-hassio-supervisor:2021.06.6: 500 Server Error for http+docker://localhost/v1.40/images/create?tag=2021.06.6&fromImage=homeassistant%2Faarch64-hassio-supervisor: Internal Server Error ("Get "https://registry-1.docker.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)")
21-07-01 14:05:01 WARNING (MainThread) [supervisor.host.network] Can't update connectivity information: Error: Timeout was reached
21-07-01 14:05:41 WARNING (MainThread) [supervisor.host.network] Can't update connectivity information: Error: Timeout was reached
21-07-01 14:06:21 WARNING (MainThread) [supervisor.host.network] Can't update connectivity information: Error: Timeout was reached
21-07-01 14:07:01 WARNING (MainThread) [supervisor.host.network] Can't update connectivity information: Error: Timeout was reached
21-07-01 14:07:41 WARNING (MainThread) [supervisor.host.network] Can't update connectivity information: Error: Timeout was reached
'''
```

### `hass-cli ha supervisor info`
```
result: ok
data:
    version: 2021.06.3
    version_latest: 2021.06.6
    update_available: true
    channel: stable
    arch: aarch64
    supported: true
    healthy: false
    ip_address: 172.30.32.2
    wait_boot: 5
    timezone: America/New_York
    logging: info
    debug: false
    debug_block: false
    diagnostics: false
    addons:
       -  name: File editor
          slug: core_configurator
          description: Simple browser-based file editor for Home Assistant
          state: started
          version: 5.3.1
          version_latest: 5.3.1
          update_available: false
          repository: core
          icon: true
          logo: true
       -  name: Terminal & SSH
          slug: core_ssh
          description: Allow logging in remotely to Home Assistant using SSH
          state: started
          version: 9.1.3
          version_latest: 9.1.3
          update_available: false
          repository: core
          icon: true
          logo: true
       -  name: Check Home Assistant configuration
          slug: core_check_config
          description: Check current Home Assistant configuration against a new version
          state: unknown
          version: 3.7.1
          version_latest: 3.7.1
          update_available: false
          repository: core
          icon: true
          logo: true
       -  name: Lutron Certificate
          slug: a0d7b954_lutron-cert
          description: Generate certificate to control Lutron Caseta bridge locally
          state: unknown
          version: 0.7.0
          version_latest: 0.7.0
          update_available: false
          repository: a0d7b954
          icon: false
          logo: false
       -  name: Let's Encrypt
          slug: core_letsencrypt
          description: Manage certificate from Let's Encrypt
          state: unknown
          version: 4.11.0
          version_latest: 4.11.0
          update_available: false
          repository: core
          icon: true
          logo: true
    addons_repositories:
       -  https://github.com/overkill32/hassio-addons
```

### `ha dns info`
```
result: ok
data:
    version: 2021.06.0
    version_latest: 2021.06.0
    update_available: false
    host: 172.30.32.3
    servers:
       -  dns://10.3.3.14
       -  dns://10.3.3.15
    locals:
       -  dns://10.3.3.14
```

### `hass-cli ha core info`
```
result: ok
data:
    version: 2021.6.2
    version_latest: 2021.6.6
    update_available: true
    machine: raspberrypi4-64
    ip_address: 172.30.32.1
    arch: aarch64
    image: homeassistant/raspberrypi4-64-homeassistant
    boot: true
    port: 8123
    ssl: true
    watchdog: true
    wait_boot: 600
    audio_input: None
    audio_output: None
    last_version: 2021.6.6
```

### `hass-cli ha os info`
```
result: ok
data:
    version: '5.13'
    version_latest: '6.1'
    update_available: true
    board: rpi4-64
    boot: B
```
