### ISSUE TITLE
Move data not possible because (internal) S2 ssd not seen as drive

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/supervisor#3686]
### Describe the issue you are experiencing

using a [Mele mini pc](https://www.mele.cn/PCHD28/124-en.html) with 128 gb emmc in the box, I run HAOS without problems.
Decided to add a M.2 SSD and move the data to that drive.

Inserted the SSD directly into the slot, did not format, nor set anything in BIOS. (believing the OS would take care of all that on the Data move.

Boots successfully, but the drive is not seen as option in the Move data, where only /dev/sda is offered

<img width="684" alt="Schermafbeelding 2022-06-21 om 17 14 15" src="https://user-images.githubusercontent.com/33354141/174862900-e26491a8-63c0-449e-ace0-7ecc756fbd9b.png">
 which cant be done because:

<img width="636" alt="Schermafbeelding 2022-06-21 om 17 19 11" src="https://user-images.githubusercontent.com/33354141/174862956-25a44ec0-ac81-4755-81f9-dd5e9f619078.png">

My guess is this is the actual active partition, so that error message is correct.

the S2 NVMe drive is seen in All Hardware:
<img width="655" alt="Schermafbeelding 2022-06-21 om 17 13 39" src="https://user-images.githubusercontent.com/33354141/174863185-0d6cecd0-0cd0-4712-ae3a-0143c9fcea8b.png">

and all details seem in order:

<img width="632" alt="Schermafbeelding 2022-06-21 om 19 49 26" src="https://user-images.githubusercontent.com/33354141/174865773-b1a049a4-d443-4779-ab31-fc75423da899.png">

Shelling in with -p 22222 `fdisk -l` results in
<img width="572" alt="Schermafbeelding 2022-06-21 om 17 29 35" src="https://user-images.githubusercontent.com/33354141/174863506-de84bb47-087b-48cc-9856-69e61d900d4a.png">

### What is the used version of the Supervisor?

supervisor-2022.06.dev2101

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 8.2

### What version of Home Assistant Core is installed?

core-2022.7.0.dev20220621

### Steps to reproduce the issue

1. described in the op
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
nothing. all green
```

### Additional information

after some serious support with pvizeli and falstaff321 I was asked to file an issue in Supervisor

this is the sda
<img width="617" alt="Schermafbeelding 2022-06-21 om 14 37 02" src="https://user-images.githubusercontent.com/33354141/174864928-48782e48-1278-47df-9ecc-ade65f745ca2.png">

<img width="582" alt="Schermafbeelding 2022-06-21 om 17 16 50" src="https://user-images.githubusercontent.com/33354141/174864989-c736ce54-0920-4a97-8ca0-abafeebca39c.png">

Ive also tried the "old fashioned" way using `datactl move` as described in [Partition method](https://github.com/home-assistant/operating-system/blob/d42f80c65e8506a6aec0c7f7f9e603107e163faf/Documentation/partition.md#using-datactl-to-move-the-data-partition) but the command isnt recognized:

<img width="569" alt="Schermafbeelding 2022-06-21 om 17 37 18" src="https://user-images.githubusercontent.com/33354141/174865082-e8d40733-e463-46e0-adf6-27c51c29f616.png">

`ha os datadisk list` returns:

<img width="205" alt="Schermafbeelding 2022-06-21 om 18 04 54" src="https://user-images.githubusercontent.com/33354141/174865543-9a299071-ec33-4b1f-8ffa-e1b64fe41651.png">

`ha hw info` results in:

[ha hw info.txt](https://github.com/home-assistant/supervisor/files/8951635/ha.hw.info.txt)

**Comment by Mariusthvdb** [comment]
latest supervisor and merged Pr Aboe show another outcome of:

```
# fdisk -l
Disk /dev/zram0: 1.9 GiB, 2040082432 bytes, 498067 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/zram1: 32 MiB, 33554432 bytes, 8192 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/zram2: 16 MiB, 16777216 bytes, 4096 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/mmcblk0: 115.23 GiB, 123731968000 bytes, 241664000 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: AB33776D-F92F-448B-8F93-AF1C50DF3F70

Device           Start       End   Sectors   Size Type
/dev/mmcblk0p1    2048     67583     65536    32M EFI System
/dev/mmcblk0p2   67584    116735     49152    24M Linux filesystem
/dev/mmcblk0p3  116736    641023    524288   256M Linux filesystem
/dev/mmcblk0p4  641024    690175     49152    24M Linux filesystem
/dev/mmcblk0p5  690176   1214463    524288   256M Linux filesystem
/dev/mmcblk0p6 1214464   1230847     16384     8M Linux filesystem
/dev/mmcblk0p7 1230848   1427455    196608    96M Linux filesystem
/dev/mmcblk0p8 1427456 241663966 240236511 114.6G Linux filesystem


Disk /dev/nvme0n1: 465.76 GiB, 500107862016 bytes, 976773168 sectors
Disk model: Samsung SSD 970 EVO Plus 500GB          
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
# 
```

**Comment by pvizeli** [comment]
Can you post the `ha hw info` ?

We don't need the output from a command on the host. You can save that time and complexity. All what we need is reachable over the HA commands on the terminal add-on.

**Comment by Mariusthvdb** [comment]
I can only copy that from a terminal outside HA, since the add-on wont let copy&paste

[ha hw info 2.txt](https://github.com/home-assistant/supervisor/files/8966381/ha.hw.info.2.txt)

**Comment by mdegat01** [comment]
It looks like the device appears in the info list here:
```yaml
- attributes:
    DEVLINKS: /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_500GB_S4EVNMFT103079E
      /dev/disk/by-id/nvme-eui.00253851219e0c07 /dev/disk/by-path/pci-0000:01:00.0-nvme-1
    DEVNAME: /dev/nvme0n1
    DEVPATH: /devices/pci0000:00/0000:00:13.0/0000:01:00.0/nvme/nvme0/nvme0n1
    DEVTYPE: disk
    DISKSEQ: "17"
    ID_MODEL: Samsung SSD 970 EVO Plus 500GB
    ID_PATH: pci-0000:01:00.0-nvme-1
    ID_PATH_TAG: pci-0000_01_00_0-nvme-1
    ID_REVISION: 2B2QEXM7
    ID_SERIAL: Samsung_SSD_970_EVO_Plus_500GB_S4EVNMFT103079E
    ID_SERIAL_SHORT: S4EVNMFT103079E
    ID_WWN: eui.00253851219e0c07
    MAJOR: "259"
    MINOR: "1"
    SUBSYSTEM: block
    TAGS: ':systemd:'
    USEC_INITIALIZED: "3631958"
  by_id: /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_500GB_S4EVNMFT103079E
  dev_path: /dev/nvme0n1
  name: nvme0n1
  subsystem: block
  sysfs: /sys/devices/pci0000:00/0000:00:13.0/0000:01:00.0/nvme/nvme0/nvme0n1
```

But is filtered out by this because of `minor`:
https://github.com/home-assistant/supervisor/blob/48eb1e89584a313e5875ed4e1bf33e1a7b4d75f2/supervisor/os/data_disk.py#L41-L48

So I guess why did it get put into that cgroup? Also if `/dev/sda` is the main disk does that mean there's a second bug here? Because the disk in use should be filtered out.
