### ISSUE TITLE
Hidden nested dictionary in addon configuration causes validation to fail if dictionary isn't populated

### ISSUE THREAD

**Issue by raman325** [home-assistant/supervisor#4606]
### Describe the issue you are experiencing

Consider the following config for an addon (most of the config removed to focus on the relevant parts):
```yaml
options:
  device: null
schema:
  device: device(subsystem=tty)
  attempts:
    openSerialPort: int(500,20000)?
    controller: int(1,3)?
    sendData: int(1,5)?
    sendDataJammed: int(1,10)?
    nodeInterview: int(1,10)?
```

Because `attempts` is not in `options`, it is hidden under `Show unused optional configuration options`. If I set the value for device, and save (without showing the unused options and entering data into the text area), I get the following error:

```
Failed to save add-on configuration, Missing option 'attempts' in root in Z-Wave JS (local_zwave_js). Got {'device': '/dev/serial/by-id/usb-Silicon_Labs_Zooz_ZST10_700_Z-Wave_Stick_0001-if00-port0'}
```

This appears to be a bug to me because we can hide `attempts` by default with the intent for the settings that are hidden to be optional, but then validation fails.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Described above

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### System Health information

N/A
