### ISSUE TITLE
Unable to Add https://github.com/hassio-addons/repository, Already in the Store

### ISSUE THREAD

**Issue by andy-cooper** [home-assistant/supervisor#4820]
### Describe the issue you are experiencing

This is a duplicate of [Issue #4622 ](https://github.com/home-assistant/supervisor/issues/4622), but since that has been closed I need to create a new one. Apologies if this is not the preferred method of doing things. I wanted to document all that I have learned and how I have worked around it in case others hit this problem. I also want to file a report that there seems to be some kind of bug here.

My home assistant community store contents vanished, and when I try to re-add it, I get an error message "Unable to Add https://github.com/hassio-addons/repository, Already in the Store"

I worked around it by adding "https://github.com/hassio-addons/./repository" as a repository URL, thus restoring my ability to use the community add-on store. However, I have not resolved the actual issue, nor do I know what caused it other than a possible file system corruption.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

See supervisor logs for what it shows w.r.t. "can't read json"

Logging in to the terminal, I executed `ha resolution info` and get the following response showing a corrupt repository (well 2. to be precise)

```
[core-ssh ~]$ ha resolution info
...
issues:
- context: store
  reference: 5c53de3b
  type: corrupt_repository
  uuid: 41b8b9ab8c7e4df38e6f69040102ff86
- context: store
  reference: a0d7b954
  type: corrupt_repository
  uuid: 964b266250ed4a24a3c96d5d08ad2d1d
suggestions:
- auto: false
  context: store
  reference: 5c53de3b
  type: execute_remove
  uuid: 5b7bd95c6a1c46c5b487d2f77b4c5c62
- auto: false
  context: store
  reference: a0d7b954
  type: execute_remove
  uuid: a23b892b481547fc998e1efd3edcb07c
unhealthy: []
unsupported: []
```

I then tried executing `ha resolution suggestion apply` with both of the suggested resolutions:

```
[core-ssh ~]$ ha resolution suggestion apply 5b7bd95c6a1c46c5b487d2f77b4c5c62
Command completed successfully.
[core-ssh ~]$ ha resolution suggestion apply a23b892b481547fc998e1efd3edcb07c
Command completed successfully.
```

Restarting the supervisor, and in fact restarting the entire system failed to clear the problems, because a subsequent ha resolution info showed the same problem.

I have worked around the problem by adding "https://github.com/hassio-addons/./repository" as a repository URL, thus restoring my ability to use the community add-on store. However, I have not resolved the actual issue, nor do I know what caused it other than a possible file system corruption.

I am concerned because a critical add-on - z-wave JS UI - is now showing "unknown" for repository in the supervisor diagnostics:

```
"a0d7b954_zwavejs2mqtt": {
          "name": "Z-Wave JS UI",
          "slug": "a0d7b954_zwavejs2mqtt",
          "version": "3.1.0",
          "version_latest": "3.1.0",
          "update_available": false,
          "state": "started",
          "repository": "unknown",
          "icon": true,
          "auto_update": true,
          "changelog": "Addon a0d7b954_zwavejs2mqtt with version latest does not exist in the store"
        }
```

similarly for `a0d7b954_logviewer`, `5c53de3b_esphome`, `a0d7b954_vscode`

I assume this means it won't get any updates. I could reinstall it, but I'm concerned that I'll lose all of my carefully-configured data. Not having tested the backup solution, I'm a little leery to do so without some advice. If I could find where those values are stored in the filesystem, I'd happily correct them to the new slug from the new community store I added.

### Anything in the Supervisor logs that might be useful for us?

```txt
24-01-15 22:17:38 ERROR (SyncWorker_3) [supervisor.utils.json] Can't read json from /data/addons/git/5c53de3b/repository.json: Expecting value: line 1 column 1 (char 0)
24-01-15 22:17:38 WARNING (SyncWorker_3) [supervisor.store.data] Can't read repository information from /data/addons/git/5c53de3b/repository.json
24-01-15 22:17:38 ERROR (SyncWorker_3) [supervisor.utils.json] Can't read json from /data/addons/git/a0d7b954/repository.json: Expecting value: line 1 column 1 (char 0)
24-01-15 22:17:38 WARNING (SyncWorker_3) [supervisor.store.data] Can't read repository information from /data/addons/git/a0d7b954/repository.json
```

### System Health information

Repairs shows "There are currently no repairs available"

### Supervisor diagnostics

[config_entry-hassio-89252243c740109eb4379069bf3a3d97.json.txt](https://github.com/home-assistant/supervisor/files/13945169/config_entry-hassio-89252243c740109eb4379069bf3a3d97.json.txt)

### Additional information

Not sure there's anything else I can add, but I can certainly gather more info if requested.
