### ISSUE TITLE
Partial Backup not working with folder addon_configs included

### ISSUE THREAD

**Issue by orclex** [home-assistant/supervisor#4915]
### Describe the issue you are experiencing

The partial backup is running until I add the existent folder _addon_configs_. Then the backup is not running and I do not find any error in logs.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

start partial backup like this:
```
alias: Backup test
description: ""
trigger:
  - platform: time
    at: "20:00:00"
condition:
  - condition: time
    weekday:
      - sat
action:
  - service: hassio.backup_partial
    metadata: {}
    data:
      compressed: true
      homeassistant: true
      location: /backup
      name: Backup test lokal folders
      folders:
        - homeassistant
        - addon_configs
mode: single
```

This should not do any backup. 
Remove line
        _- addon_configs_
 in folders and the backup is running.

### Anything in the Supervisor logs that might be useful for us?

```txt
With folder addon_configs in backup included, there is no line in logs attached.

Without folder addon_configs:

24-02-23 22:39:32 INFO (MainThread) [supervisor.backups.manager] Backup 1c56144e starting stage addon_repositories
24-02-23 22:39:32 INFO (MainThread) [supervisor.backups.manager] Backup 1c56144e starting stage docker_config
24-02-23 22:39:32 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug 1c56144e
24-02-23 22:39:32 INFO (MainThread) [supervisor.backups.manager] Backup 1c56144e starting stage home_assistant
24-02-23 22:39:32 INFO (MainThread) [supervisor.homeassistant.module] Backing up Home Assistant Core config folder
24-02-23 22:39:39 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done
24-02-23 22:39:39 INFO (MainThread) [supervisor.backups.manager] Backup 1c56144e starting stage finishing_file
24-02-23 22:39:39 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 1c56144e completed
```

## System Information

version | core-2024.2.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1395
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 938.2 GB
disk_used | 241.9 GB
healthy | true
supported | true
board | rpi5-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.1.1), FTP (5.0.1), File editor (5.8.0), Samba share (12.3.0), Syncthing (1.18.2), Mosquitto broker (6.4.0), VLC (0.3.0), Studio Code Server (5.15.0), Mopidy (2.2.0), Matter Server (5.2.0), Filebrowser (2.23.0_12), Logitech Media Server (8.3.1.60), Squeezelite (0.0.18), Samba Backup (5.2.0), Log Viewer (0.17.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 1
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 14. Februar 2024 um 05:17
-- | --
current_recorder_run | 23. Februar 2024 um 17:30
estimated_db_size | 370.95 MiB
database_engine | sqlite
database_version | 3.44.2

</details>
