### ISSUE TITLE
Backup mount as default backup location causes partial system failure

### ISSUE THREAD

**Issue by TomK** [home-assistant/supervisor#5030]
### Describe the issue you are experiencing

i've been having periodic crashes since the last supervisor update. i've narrowed it down to a NAS mount.

 I have four mounts on my WD MyCloud Home Duo:
```yaml
default_backup_mount: null
mounts:
- name: frigate
  read_only: false
  server: 192.168.0.25
  share: localuser/frigate
  state: active
  type: cifs
  usage: media
  version: null
- name: ha_backup
  read_only: false
  server: 192.168.0.25
  share: localuser/ha-backup
  state: active
  type: cifs
  usage: backup
  version: null
- name: plex
  read_only: false
  server: 192.168.0.25
  share: localuser/Plex
  state: active
  type: cifs
  usage: share
  version: null
- name: doubletake
  read_only: false
  server: 192.168.0.25
  share: localuser/double-take
  state: active
  type: cifs
  usage: media
  version: null
```

i removed all of them and re-added the one named `ha_backup`, within few moments and the system becomes partly unresponsive. I say partly, because some ui elements load, but many pages timeout, and eventually report: "Unable to load the panel source: /api/hassio/app/entrypoint.js"
On the storage page, i've also received the error: "Network storage is not supported on this host"

I have reinstated the other mounts, `frigate`, `plex` and `doubletake`, and the system remains stable. So for now, i am simply backing up onto my primary disk.

I'd like to note, this setup was working fine until the recent supervisor update.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. create a backup share (cifs)
2. set share as default backup location
3. wait for system to behave unusually
...

### Anything in the Supervisor logs that might be useful for us?

I run a pretty basic setup, initially installed using https://www.home-assistant.io/installation/generic-x86-64 on an Lenovo ThinkCentre M710q Tiny

## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1399
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 13 May 2024 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-10.ui.nabu.casa
certificate_status | ready
instance_id | 5e00b2e260ae4f1194818e5fbe562683
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | beta
supervisor_version | supervisor-2024.04.2
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 109.3 GB
disk_used | 52.5 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.112.1), Studio Code Server (5.15.0), NGINX Home Assistant SSL proxy (3.9.0), Node-RED (17.0.12), Advanced SSH & Web Terminal (17.2.0), Mosquitto broker (6.4.0), ESPHome (2024.4.0), Google Cloud DNS (1.0.2), chrony (3.0.1), Exadel CompreFace (1.1.0), Transmission (dev), Matter Server (5.5.1), Whisper (2.0.0), Piper (1.5.0), Asterisk (4.2.0), Plex Media Server (3.5.0), Silicon Labs Multiprotocol (2.4.5), openWakeWord (1.10.0), PS5 MQTT (1.3.3), AdGuard Home (5.0.6), Frigate (0.13.2), CodeProject AI.Server (CPU) (2.5.1), Double Take (1.13.11.8)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 3
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 11 April 2024 at 08:42
-- | --
current_recorder_run | 21 April 2024 at 04:12
estimated_db_size | 550.19 MiB
database_engine | sqlite
database_version | 3.44.2

</details>
