### ISSUE TITLE
Supervisor jobs that never run

### ISSUE THREAD

**Issue by tescophil** [home-assistant/supervisor#5570]
### Describe the issue you are experiencing

```ha jobs info``` produces thousands of line of output for jobs with ```stage: null```

This looks similar to a bug I reported back in September 2023

https://github.com/home-assistant/supervisor/issues/4564#issue-1899851866

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. run ha jobs info
2.
3.
...

Small extract of the output

```
~ # ha jobs info
ignore_conditions: []
jobs:
- child_jobs:
  - child_jobs: []
    done: true
    errors: []
    name: backup_store_homeassistant
    progress: 0
    reference: 9faf7b5d
    stage: null
    uuid: ea7f01e99eb6483fbccb34b7392a1abb
  - child_jobs:
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: core_duckdns
      stage: null
      uuid: 0150527494b34c82b2028db0479194a2
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: core_configurator
      stage: null
      uuid: 43a77c15af854e5ab51505ed2e67c240
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: cebe7a76_hassio_google_drive_backup
      stage: null
      uuid: ddf3f6bf02cf485b87123825b3534fdb
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: a0d7b954_ssh
      stage: null
      uuid: b3a262be3ef9496c85ef4006f1dc06b9
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: ca021f77_snmpd
      stage: null
      uuid: 2a5ca438585b4c8d877c745d553b4a4d
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: core_openwakeword
      stage: null
      uuid: 51030b2dbf0d4b1e871e719bf05b2370
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: 491eb00d_hamh
      stage: null
      uuid: 213f43bcc79245b78673b552247dba7f
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: core_whisper
      stage: null
      uuid: b5555d8ccecb42879f4ac5f8ff2d2d1c
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: core_piper
      stage: null
      uuid: 07dc25255f9d4b76a9da829c9545cb12
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: a0d7b954_glances
      stage: null
      uuid: c917492ca8644775af0adb6760e3cf2e
    done: true
    errors: []
    name: backup_store_addons
    progress: 0
    reference: 9faf7b5d
    stage: null
    uuid: 971d9300553a4c45962cd5e50182f976
  - child_jobs:
    - child_jobs: []
      done: true
      errors: []
      name: backup_folder_save
      progress: 0
      reference: share
      stage: null
      uuid: 94f55e5595314b1b98f9fb01544b2d72
    - child_jobs: []
      done: true
      errors: []
      name: backup_folder_save
      progress: 0
      reference: addons/local
      stage: null
      uuid: 424057a1f340450ba37e7c0db6bbf9a2
    - child_jobs: []
      done: true
      errors: []
      name: backup_folder_save
      progress: 0
      reference: ssl
      stage: null
      uuid: 401d23878c0448c6a1bb793b355d4111
    - child_jobs: []
      done: true
      errors: []
      name: backup_folder_save
      progress: 0
      reference: media
      stage: null
      uuid: 34ee2044c4c540d980babb0e32352dad
    done: true
    errors: []
    name: backup_store_folders
    progress: 0
    reference: 9faf7b5d
    stage: null
    uuid: 610847dfb46644fb953b533465bbf21d
  done: true
  errors: []
  name: backup_manager_full_backup
  progress: 0
  reference: 9faf7b5d
  stage: finishing_file
  uuid: a2d6828542c0406aa629d61b40979717
- child_jobs:
  - child_jobs: []
    done: true
    errors: []
    name: backup_store_homeassistant
    progress: 0
    reference: 5fdb63d5
    stage: null
    uuid: 0e29a77f8b6d4bd8b3d7046e5f98d38d
  - child_jobs:
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: core_duckdns
      stage: null
      uuid: e394c616c66b42668e4efa8218fd292c
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: core_configurator
      stage: null
      uuid: f3da7b56e5b04459a45ed256df9900ca
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: cebe7a76_hassio_google_drive_backup
      stage: null
      uuid: e6b7d318103945e5b62ead4b7e910304
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: a0d7b954_ssh
      stage: null
      uuid: 8335841b41ab4e59a1c2c5c70b7d2b08
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: ca021f77_snmpd
      stage: null
      uuid: 5799c3abf3c74c35a2880b3666040ac5
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: core_openwakeword
      stage: null
      uuid: 1e4a0ff13a744702949c0abe181c74f8
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: 491eb00d_hamh
      stage: null
      uuid: 8800eed3ff6a426a8baa8c4ef1a3d8e9
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: core_whisper
      stage: null
      uuid: e48bd30e7f5c4fa98711ccc06240cc17
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: core_piper
      stage: null
      uuid: 2b3257c3b127499abff1a50ea44ae87a
    - child_jobs: []
      done: true
      errors: []
      name: backup_addon_save
      progress: 0
      reference: a0d7b954_glances
      stage: null
      uuid: 805246c2c28a4e2e969310b470d56ddb
    done: true
    errors: []
    name: backup_store_addons
    progress: 0
    reference: 5fdb63d5
    stage: null
    uuid: 1379232949264faba94edf375bc08789
```

### Anything in the Supervisor logs that might be useful for us?

```txt
Last 100 lines

[32m2025-01-23 04:00:00.342 INFO (MainThread) [supervisor.backups.manager] Backup 5c9a802d starting stage home_assistant[0m
[32m2025-01-23 04:00:00.354 INFO (MainThread) [supervisor.homeassistant.module] Backing up Home Assistant Core config folder[0m
[32m2025-01-23 04:00:04.389 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done[0m
[32m2025-01-23 04:00:04.393 INFO (MainThread) [supervisor.backups.manager] Backup 5c9a802d starting stage addons[0m
[32m2025-01-23 04:00:04.399 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_duckdns[0m
[32m2025-01-23 04:00:04.432 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_duckdns[0m
[32m2025-01-23 04:00:04.438 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_configurator[0m
[32m2025-01-23 04:00:04.440 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_configurator[0m
[32m2025-01-23 04:00:04.446 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on cebe7a76_hassio_google_drive_backup[0m
[32m2025-01-23 04:00:04.449 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon cebe7a76_hassio_google_drive_backup[0m
[32m2025-01-23 04:00:04.455 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_ssh[0m
[32m2025-01-23 04:00:04.460 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_ssh[0m
[32m2025-01-23 04:00:04.468 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on ca021f77_snmpd[0m
[32m2025-01-23 04:00:04.472 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon ca021f77_snmpd[0m
[32m2025-01-23 04:00:04.479 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_openwakeword[0m
[32m2025-01-23 04:00:04.483 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_openwakeword[0m
[32m2025-01-23 04:00:06.901 INFO (SyncWorker_2) [supervisor.docker.manager] Export image <generator object APIClient._stream_raw_result at 0x7f1bc0c84d60> to /data/tmp/tmpgxu5rmy9/image.tar[0m
[32m2025-01-23 04:00:07.164 INFO (SyncWorker_2) [supervisor.docker.manager] Export image <generator object APIClient._stream_raw_result at 0x7f1bc0c84d60> done[0m
[32m2025-01-23 04:00:07.169 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on 491eb00d_hamh[0m
[32m2025-01-23 04:00:08.042 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon 491eb00d_hamh[0m
[32m2025-01-23 04:00:08.048 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_whisper[0m
[32m2025-01-23 04:00:08.051 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_whisper[0m
[32m2025-01-23 04:00:08.056 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_piper[0m
[32m2025-01-23 04:00:08.061 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_piper[0m
[32m2025-01-23 04:00:08.061 INFO (MainThread) [supervisor.backups.manager] Backup 5c9a802d starting stage folders[0m
[32m2025-01-23 04:00:08.062 INFO (SyncWorker_6) [supervisor.backups.backup] Backing up folder share[0m
[32m2025-01-23 04:00:08.069 INFO (SyncWorker_6) [supervisor.backups.backup] Backup folder share done[0m
[32m2025-01-23 04:00:08.069 INFO (SyncWorker_2) [supervisor.backups.backup] Backing up folder addons/local[0m
[32m2025-01-23 04:00:08.071 INFO (SyncWorker_2) [supervisor.backups.backup] Backup folder addons/local done[0m
[32m2025-01-23 04:00:08.072 INFO (SyncWorker_1) [supervisor.backups.backup] Backing up folder ssl[0m
[32m2025-01-23 04:00:08.074 INFO (SyncWorker_1) [supervisor.backups.backup] Backup folder ssl done[0m
[32m2025-01-23 04:00:08.075 INFO (SyncWorker_5) [supervisor.backups.backup] Backing up folder media[0m
[32m2025-01-23 04:00:08.077 INFO (SyncWorker_5) [supervisor.backups.backup] Backup folder media done[0m
[32m2025-01-23 04:00:08.077 INFO (MainThread) [supervisor.backups.manager] Backup 5c9a802d starting stage finishing_file[0m
[32m2025-01-23 04:00:08.079 INFO (MainThread) [supervisor.backups.manager] Creating full backup with slug 5c9a802d completed[0m
[32m2025-01-23 04:00:08.359 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2025-01-23 04:00:08.365 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m2025-01-23 04:00:08.367 INFO (MainThread) [supervisor.api.middleware.security] /backups/5c9a802d/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2025-01-23 04:00:08.877 INFO (MainThread) [supervisor.api.middleware.security] /backups/f6a4d941 access from cebe7a76_hassio_google_drive_backup[0m
[32m2025-01-23 04:00:08.902 INFO (MainThread) [supervisor.api.middleware.security] /backups/5c9a802d/download access from cebe7a76_hassio_google_drive_backup[0m
[32m2025-01-23 04:00:08.902 INFO (MainThread) [supervisor.api.backups] Downloading backup 5c9a802d[0m
[32m2025-01-23 04:03:45.835 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2025-01-23 04:03:45.838 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m2025-01-23 04:03:45.842 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2025-01-23 04:03:45.844 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m2025-01-23 04:26:12.703 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m2025-01-23 04:53:19.538 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running[0m
[32m2025-01-23 04:53:19.538 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor[0m
[32m2025-01-23 04:53:19.546 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system[0m
[32m2025-01-23 04:53:19.546 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system[0m
[32m2025-01-23 04:53:19.546 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system[0m
[32m2025-01-23 04:53:19.546 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system[0m
[32m2025-01-23 04:53:19.547 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system[0m
[32m2025-01-23 04:53:19.547 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core[0m
[32m2025-01-23 04:53:19.547 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server[0m
[32m2025-01-23 04:53:19.624 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon[0m
[32m2025-01-23 04:53:19.625 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server[0m
[32m2025-01-23 04:53:19.626 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system[0m
[32m2025-01-23 04:53:19.627 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m2025-01-23 04:53:19.627 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running[0m
[32m2025-01-23 04:53:19.696 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m2025-01-23 04:53:19.696 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running[0m
[32m2025-01-23 04:53:19.696 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m2025-01-23 04:56:12.903 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m2025-01-23 05:06:41.562 INFO (MainThread) [supervisor.host.info] Updating local host information[0m
[32m2025-01-23 05:06:41.836 INFO (MainThread) [supervisor.host.services] Updating service information[0m
[32m2025-01-23 05:06:41.839 INFO (MainThread) [supervisor.host.network] Updating local network information[0m
[32m2025-01-23 05:06:41.899 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
[32m2025-01-23 05:06:41.903 INFO (MainThread) [supervisor.host.manager] Host information reload completed[0m
[32m2025-01-23 05:26:13.078 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m2025-01-23 05:39:14.547 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh[0m
[32m2025-01-23 05:39:14.550 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh[0m
[32m2025-01-23 05:39:14.552 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from a0d7b954_ssh[0m
[32m2025-01-23 05:39:14.554 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from a0d7b954_ssh[0m
[32m2025-01-23 05:39:24.006 INFO (MainThread) [supervisor.api.middleware.security] /dns/info access from a0d7b954_ssh[0m
[32m2025-01-23 05:39:50.470 INFO (MainThread) [supervisor.api.middleware.security] /jobs/info access from a0d7b954_ssh[0m
[32m2025-01-23 05:41:38.013 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh[0m
[32m2025-01-23 05:41:38.015 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh[0m
[32m2025-01-23 05:41:38.016 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from a0d7b954_ssh[0m
[32m2025-01-23 05:41:38.017 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from a0d7b954_ssh[0m
[32m2025-01-23 05:41:49.305 INFO (MainThread) [supervisor.api.middleware.security] /jobs/info access from a0d7b954_ssh[0m
[32m2025-01-23 05:42:09.021 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2025-01-23 05:42:09.025 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m2025-01-23 05:53:19.699 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running[0m
[32m2025-01-23 05:53:19.700 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor[0m
[32m2025-01-23 05:53:19.707 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system[0m
[32m2025-01-23 05:53:19.708 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system[0m
[32m2025-01-23 05:53:19.708 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system[0m
[32m2025-01-23 05:53:19.708 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system[0m
[32m2025-01-23 05:53:19.708 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system[0m
[32m2025-01-23 05:53:19.708 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core[0m
[32m2025-01-23 05:53:19.709 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server[0m
[32m2025-01-23 05:53:19.769 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon[0m
[32m2025-01-23 05:53:19.770 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server[0m
[32m2025-01-23 05:53:19.771 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system[0m
[32m2025-01-23 05:53:19.771 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m2025-01-23 05:53:19.771 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running[0m
[32m2025-01-23 05:53:19.841 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m2025-01-23 05:53:19.842 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running[0m
[32m2025-01-23 05:53:19.842 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
```

## System Information

version | core-2025.1.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.1
os_name | Linux
os_version | 6.6.66-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.3
Stage | running
Available Repositories | 1506
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 234.0 GB
disk_used | 14.5 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.18.0), File editor (5.8.0), Home Assistant Google Drive Backup (0.112.1), Advanced SSH & Web Terminal (20.0.0), SNMPD (0.4.0), openWakeWord (1.10.0), Home-Assistant-Matter-Hub (3.0.0-alpha.63), Whisper (2.4.0), Piper (1.5.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 5
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 20 January 2025 at 10:55
-- | --
current_recorder_run | 22 January 2025 at 09:32
estimated_db_size | 242.98 MiB
database_engine | sqlite
database_version | 3.47.1

</details>

<details><summary>Sonoff</summary>

version | 3.8.2 (c4b6fda)
-- | --
cloud_online | 13 / 14
local_online | 12 / 12

</details>

### Supervisor diagnostics

[config_entry-hassio-b33f8491d34551b041583e82c4ee1b9b.json](https://github.com/user-attachments/files/18515791/config_entry-hassio-b33f8491d34551b041583e82c4ee1b9b.json)
