### ISSUE TITLE
Automation Crashes/Runs Out Of Memory of HA when using Generic Thermostat

### ISSUE THREAD

**Issue by comet424** [home-assistant/supervisor#5624]
### Describe the issue you are experiencing

so i run automation to set the temperatures.. since the Generic Thermostat built in is missing some variables, i had reported it for additional variables but i dunno if it ever happen or so,  so i had to make work arounds... it saves temperature away and home to a txt file and then 2 sensors use read the file and set the away and none to override the target temps

now if when using 4 gig of ram..  the vm runs out of ram...  so i upped it to 8gigs... when running  and u run the automation  it would run out of memory and stop working..  or it would instantly go into connection lost: reconnecting.

i posted topic in the forums
https://community.home-assistant.io/t/my-automation-keeps-crashing-ha-runs-out-of-memory-need-help/845252/15

here is the video or how HA doesnt toggle into Away mode.  it stays in Home(none) and it uses this config
[https://1drv.ms/f/c/2759db01e8e27b46/EqrInQquK59AlRz6mJ-MnGQB12iMNBwd7JYZQM1-wOECSA?e=zoviYa](url)
```
alias: "!!test"
description: ""
triggers:
  - trigger: state
    entity_id:
      - climate.moms_furnace
    attribute: preset_mode
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: climate.moms_furnace
            attribute: preset_mode
            state: away
        sequence:
          - action: climate.set_temperature
            metadata: {}
            data:
              temperature: "{{states('sensor.away_temperature_house') }}"
            target:
              entity_id: climate.moms_furnace
      - conditions:
          - condition: state
            entity_id: climate.moms_furnace
            attribute: preset_mode
            state: none
        sequence:
          - action: climate.set_temperature
            metadata: {}
            data:
              temperature: "{{states('sensor.home_temperature_house') }}"
            target:
              entity_id: climate.moms_furnace
mode: single
```

here is a single automation that used to work too.. where it waits from none to Away
[https://1drv.ms/f/c/2759db01e8e27b46/EgwPcEHttgpKr7Qza42sT6ABWic611f2njw844Ryxumppg?e=IOP6DQ](url)
code is
```
alias: "!!!test again"
description: ""
triggers:
  - trigger: state
    entity_id:
      - climate.moms_furnace
    attribute: preset_mode
    to: away
    from: none
conditions: []
actions:
  - action: climate.set_temperature
    metadata: {}
    data:
      temperature: "{{states('sensor.away_temperature_house') }}"
    target:
      entity_id: climate.moms_furnace
mode: single
```

and the code the automation that causes HA to crash instantly  or run out of memory and the gui is gone  the console still runs  but if you try to restart the gui      like core restart    it never starts up  you need to physically restart it...
here i force when you press button  and it goes to Away to Force the button to Away.  well it doesnt move   but it will crash HA instantly.. with 8 gig of ram..  or 4 gig ram  and it crashes but shows in the console that it ran out of memory
```
alias: "!!test"
description: ""
triggers:
  - trigger: state
    entity_id:
      - climate.moms_furnace
    attribute: preset_mode
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: climate.moms_furnace
            attribute: preset_mode
            state: away
        sequence:
          - action: climate.set_temperature
            metadata: {}
            data:
              temperature: "{{states('sensor.away_temperature_house') }}"
            target:
              entity_id: climate.moms_furnace
          - action: climate.set_preset_mode
            metadata: {}
            data:
              preset_mode: away
            target:
              entity_id: climate.moms_furnace
      - conditions:
          - condition: state
            entity_id: climate.moms_furnace
            attribute: preset_mode
            state: none
        sequence:
          - action: climate.set_temperature
            metadata: {}
            data:
              temperature: "{{states('sensor.home_temperature_house') }}"
            target:
              entity_id: climate.moms_furnace
          - action: climate.set_preset_mode
            metadata: {}
            data:
              preset_mode: none
            target:
              entity_id: climate.moms_furnace
mode: single

```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. make the automation
2. install simple generic thermostat and make a page
3. click Away toggle button,  
...

### Anything in the Supervisor logs that might be useful for us?

```txt
dont know as soon as you run it crashes  with the last automation.. above other then that it doesnt show info
```

### System Health information

There are currently no repairs pending
